#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Seed Refinery database when we first deploy
# Notice that we run 'rake db:drop' on production database.
# Be very, very careful.
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
if [ ! -f db_seeded ]; then
  bundle exec rake db:drop RAILS_ENV="production"
  bundle exec rake db:migrate RAILS_ENV="production"
  bundle exec rake db:setup RAILS_ENV="production"
  touch db_seeded
  chmod 400 db_seeded
fi
popd > /dev/null
